media-streaming:
  video-directory-on-file-system: '/Users/johnny/Movies/Mine'

# Configure logging level of Media Streaming
logging:
  config: classpath:configuration/logback/logback.xml
  level:
    com.github.johnnymillergh.boot.mediastreamingspringbootautoconfigure: DEBUG

server:
  shutdown: graceful
