# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0.8
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.8'
        architecture: x64
    - name: Build and Test with Maven
      run: mvn --batch-mode --show-version compile --file pom.xml

  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0.8
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.8'
        architecture: x64
    - name: Check Dependencies version with Versions Maven Plugin
      run: mvn versions:display-dependency-updates versions:display-parent-updates -f pom.xml
